# Numpy 개요

In [ ]:
#데이터 전처리
#numpy는 배열/수치계산을 효율적으로 
#pandas
#openCV:이미지데이터를 다룰 수 있는 라이브러리

In [2]:
import numpy as np
np.__version__

'1.26.4'

## ndim(dimention, rank)
몇 차원인지 반환

In [4]:
a = np.array(0)

In [5]:
a, a.ndim, type(a) #NDIM은 차원을 의

(array(0), 0, numpy.ndarray)

In [6]:
a = np.array([2, 4, 6])
a, a.ndim, type(a)

(array([2, 4, 6]), 1, numpy.ndarray)

In [10]:
a = [[1,2,3], [4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [9]:
a = np.array([[1,2,3], [4,5,6]])
a, a.ndim, type(a)

(array([[1, 2, 3],
        [4, 5, 6]]),
 2,
 numpy.ndarray)

In [13]:
a = np.array([[[1,2,3], [4,5,6]],[[1,2,3], [4,5,6]]])
a, a.ndim, type(a)

(array([[[1, 2, 3],
         [4, 5, 6]],
 
        [[1, 2, 3],
         [4, 5, 6]]]),
 3,
 numpy.ndarray)

In [14]:
a.shape#2행3열이 두개가 있어

(2, 2, 3)

## shape

In [17]:
a = np.array(3)
a, a.shape #a.shape 행렬아님

(array(3), ())

In [20]:
a = np.array([ 1, 3, 5, 7, 9 ])
a, a.shape

(array([1, 3, 5, 7, 9]), (5,))

In [21]:
a = np.array([[1,2,3], [4,5,6]])
a, a.shape

(array([[1, 2, 3],
        [4, 5, 6]]),
 (2, 3))

In [22]:
a = np.array([[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]], [[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]])
a, a.shape # 2개의 3행 4열

(array([[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],
 
        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]),
 (2, 3, 4))

In [23]:
a.ndim

3

## 넘파이 배열
리스트를 넘파이 배열로 생성 np.array(리스트)
관련 속성 : ndim 차원 반환 int , size 전체 길이 반환 int, shape 구조 반환 tuple

In [24]:
# 1차원 리스트 객체(이터러블)
myList = [10, 56, 77, 23, 44]
print(myList, type(myList), len(myList))

[10, 56, 77, 23, 44] <class 'list'> 5


In [26]:
myArr = np.array(myList)
print(myArr, type(myArr), len(myArr))
print(f'차원={myArr.ndim}, 구조={myArr.shape}, size={myArr.size}, 길이={len(myArr)}')

[10 56 77 23 44] <class 'numpy.ndarray'> 5
차원=1, 구조=(5,), size=5, 길이=5


In [27]:
# 2차원 리스트 객체(이터러블)
myList2 = [[1,2,3 ],[10,20,30],[100,200,300]]
myList2, len(myList2)

([[1, 2, 3], [10, 20, 30], [100, 200, 300]], 3)

In [28]:
myArr2 = np.array(myList2) #사이즈는 요소의 갯수, 여기서 길이는 행의 갯
print(myArr2, type(myArr2), len(myArr2))
print(f'차원= {myArr2.ndim}, 구조 = {myArr2.shape}, size = {myArr2.size}, 길이={len(myArr2)}' )

[[  1   2   3]
 [ 10  20  30]
 [100 200 300]] <class 'numpy.ndarray'> 3
차원= 2, 구조 = (3, 3), size = 9, 길이=3


In [29]:
# 2차원 리스트에서 각 행의 수가 다를 경우?
myList21 = [ [1,2,3,4],[10,20,30,40,50],[100,200,]]
print(myList21, type(myList21), len(myList21))

[[1, 2, 3, 4], [10, 20, 30, 40, 50], [100, 200]] <class 'list'> 3


In [30]:
# 길이가 달라 어레이로 변환 안됨 그래서 에러 리턴 
myArr21 = np.array(myList21)
print(myArr21, type(myArr21), len(myArr21))
print(f'차원= {myArr21.ndim}, 구조 = {myArr21.shape}, size = {myArr21.size}')

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

## 넘파이 배열과 리스트와의 차이점
배열간의 연산 가능 "브로드캐스팅", 요소별 연산(element-wise)
넘파이 메서드 사용 가능 : 평균, 상관계수, 분산, 표준편차 등
리스트는 자료형 혼합 가능, 넘파이배열은 하나의 자료형만 가능

In [31]:
# 리스트의 산술연산자 +, * 
listA = [10, 30, 50]
listB = [1, 2, 3]
print(listA + listB) # 리스트의 + 연산자는 조인역할
print(listA + 2) # 불가

[10, 30, 50, 1, 2, 3]


TypeError: can only concatenate list (not "int") to list

In [32]:
print(listA * 2) # 해당 리스트의 반복
print(listA * listB) # 불가

[10, 30, 50, 10, 30, 50]


TypeError: can't multiply sequence by non-int of type 'list'

In [33]:
# 넘파이의 산술연산
arrA = np.array([1, 2, 3])
print(arrA + 2)
print(arrA * 2)

[3 4 5]
[2 4 6]


In [34]:
arrB = np.array([4, 5, 6])
print(arrA + arrB)
print(arrA * arrB)
print(arrA / arrB)
print(arrA // arrB) # 몫
print(arrA % arrB) # 나머지 넘파이는 리스트와 다르게 숫자계산 다

[5 7 9]
[ 4 10 18]
[0.25 0.4  0.5 ]
[0 0 0]
[1 2 3]


## dtype

In [37]:
# 자료형 테스트
myList_c = ['안녕', 100, 3.14, True, False] # 리스트는 혼합된 형 그대로 유지
print(myList_c)

['안녕', 100, 3.14, True, False]


In [38]:
myArr_c = np.array(myList_c) # 넘파이배열은 '문자열'로 통일 자동형변환 더큰 자료형으로 통일 시킴
print(myArr_c, type(myArr_c), myArr_c.dtype) #'안녕'이 문자열이라 제일 커서 전부 문자열로 통

['안녕' '100' '3.14' 'True' 'False'] <class 'numpy.ndarray'> <U32


In [39]:
# 정수와 실수가 혼합된 넘파이 배열
myArr_d = np.array([100, 3.14, 23.5, 0])
print(myArr_d, type(myArr_d), myArr_d.dtype) # 정수와 실수 혼합시, 더 큰 실수형으로 통일 자동형변환

[100.     3.14  23.5    0.  ] <class 'numpy.ndarray'> float64


## Inf와 NaN
넘파이에서는 무한대를 표현하기 위한 np.inf(infinity)와 정의할 수 없는 숫자를 나타내는 np.nan(not a number)을 사용할 수 있다.
다음 예와 같이 1을 0으로 나누려고 하거나 0에 대한 로그 값을 계산하면 무한대인 np.inf이 나온다.
0을 0으로 나누려고 시도하면 np.nan이 나온다.

In [40]:
np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])

C:\Users\sumin\AppData\Local\Temp\ipykernel_26052\2068585620.py:1: RuntimeWarning: divide by zero encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])
C:\Users\sumin\AppData\Local\Temp\ipykernel_26052\2068585620.py:1: RuntimeWarning: invalid value encountered in divide
  np.array([0, 1, -1, 0]) / np.array([1, 0, 0, 0])


array([  0.,  inf, -inf,  nan])

In [41]:
np.log(0)

C:\Users\sumin\AppData\Local\Temp\ipykernel_26052\2933082444.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(0)


-inf

In [42]:
np.exp(-np.inf)

0.0

## 기술통계

In [44]:
x = np.array([18,   5,  10,  23,  19,  -8,  10,   0,   0,   5,   2,  15,   8,
              2,   5,   4,  15,  -1,   4,  -7, -24,   7,   9,  -6,  23, -13])

In [45]:
x.mean()

4.8076923076923075

In [46]:
np.mean(x)  # 평균

4.8076923076923075

In [48]:
x.mean()

4.8076923076923075

In [47]:
np.var(x)  # 분산

115.23224852071006

In [49]:
np.std(x)  # 표준 편차

10.734628476137871

In [50]:
np.max(x)  # 최댓값

23

In [51]:
np.min(x)  # 최소값

-24

In [52]:
np.median(x)  # 중앙값

5.0

## 사분위수
사분위수(quartile)는 데이터를 가장 작은 수부터 가장 큰 수까지 크기가 커지는 순서대로 정렬하였을 때 1/4, 2/4, 3/4 위치에 있는 수를 말한다.
각각 1사분위수, 2사분위수, 3사분위수라고 한다.
1/4의 위치란 전체 데이터의 수가 만약 100개이면 25번째 순서, 즉 하위 25%를 말한다. 따라서 2사분위수는 중앙값과 같다.

때로는 위치를 1/100 단위로 나눈 백분위수(percentile)을 사용하기도 한다. 1사분위수는 25% 백분위수와 같다.

In [54]:
np.percentile(x, 0)  # 최소값 0에 대한 위치를 알려

-24.0

In [55]:
np.percentile(x, 25)  # 1사분위 수

0.0

In [56]:
np.percentile(x, 50)  # 2사분위 수

5.0

In [57]:
np.percentile(x, 75)  # 3사분위 수

10.0

In [58]:
np.percentile(x, 100)  # 최댓값

23.0

## 넘파이 함수로 배열 만들기
np.ones(n) , np.ones((x, y))
np.zeros(n) , np.zeros((x, y))
np.empty(n) , np.empty((x, y))
np.aranges(start, end step)

reshape(x, y) # 차원 확대
flatten(x, y) # 차원 축소

In [59]:
# 1로 메모리 초기화, 넘파이 함수로 배열을 만들때에는 디폴트가 실수형
print(np.ones(10), np.ones(10).dtype) #자주사용 

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] float64


In [60]:
print(np.ones((2,4)), np.ones((2,4)).dtype) #2행4열로 만든다.

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]] float64


In [ ]:
#다른것은 계산하고 특정부분을 유지하고싶을때 ones를 쓴다.

In [61]:
# 0으로 메모리 초기화 /유지안하고싶을때
print(np.zeros(10), np.zeros(10).dtype)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64


In [62]:
print(np.zeros((3,3)), np.zeros((3,3)).dtype)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64


In [63]:
# 메모리가 비어있음 -> 메모리가 초기화 되지 않는다. empty와 zeros는 다른개념
print(np.empty(10), np.empty(10).dtype)
print(np.empty((3,3)), np.empty((3,3)).dtype)
print(np.empty((3,3)))
print(np.empty((3,3), dtype=int))  # 기존 메모리에 있던 값을 출력한다.(정확히 알수 x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] float64
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[          0           0   -58190784]
 [        536   -58188624         536]
 [  -58190304         536 -2090074112]]


In [64]:
# 리스트+레인지
print( list(range(1,21)), type(list(range(1,21))) )

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20] <class 'list'>


In [65]:
# 1~20으로 구성된 4행 5열의 넘파이 배열print(np.array(list(range(1,21))), type(list(range(1,21))))
print(np.arange(20), type(np.arange(20)))
print(np.arange(1, 20), type(np.arange(1, 20)))
print(np.arange(1, 20, 2), type(np.arange(1, 20,2)))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] <class 'numpy.ndarray'>
[ 1  3  5  7  9 11 13 15 17 19] <class 'numpy.ndarray'>


In [66]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [69]:
# linspace 명령이나 logspace 명령은 선형 구간 혹은 로그 구간을 지정한 구간의 수만큼 분할한다.
np.linspace(0, 100, 5)  # 시작, 끝(포함), 갯수
# 도표만들때 시각화 할때 쓰임 0~100을 5개로 나오게함

array([  0.,  25.,  50.,  75., 100.])

In [70]:
np.logspace(0.1, 1, 10)

array([ 1.25892541,  1.58489319,  1.99526231,  2.51188643,  3.16227766,
        3.98107171,  5.01187234,  6.30957344,  7.94328235, 10.        ])

## reshape 구조의 재배열
```
reshape함수는 np.reshape(변경할 배열, 차원) 또는 배열.reshape(차원)으로 사용 할 수 있으며,
현재의 배열의 차원(1차원,2차원,3차원)을 변경하여 행렬을 반환하거나 하는 경우에 많이 이용되는 함수이다.
```

In [71]:
# 0~49까지 구성된 넘파이 배열
arr = np.arange(50)
print(arr, len(arr), arr.size)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49] 50 50


In [72]:
arr, arr.ndim, arr.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 1,
 (50,))

In [74]:
arr = arr.reshape(10,5) #10행 5열로 바꿔줘 , 2차원으로바뀜
arr, arr.ndim, arr.shape

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49]]),
 2,
 (10, 5))

In [75]:
arr2 = arr.reshape(5,10)
arr2, arr2.ndim, arr2.shape

(array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
        [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]]),
 2,
 (5, 10))

In [76]:
# 2차원 -> 1차원
# 넘파이배열.flatten()
arr3 = arr2.flatten()
arr3, arr3.shape, arr3.ndim

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
        34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]),
 (50,),
 1)

In [77]:
# 1~100 사이의 짝수로 된 넘파이 배열 생성
np.arange(2,101,2)

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [78]:
np.arange(2,101,2).reshape(5,10)

array([[  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [ 22,  24,  26,  28,  30,  32,  34,  36,  38,  40],
       [ 42,  44,  46,  48,  50,  52,  54,  56,  58,  60],
       [ 62,  64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98, 100]])

In [79]:
np.arange(1, 31)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [83]:
# 2차원인데 1개 칼럼의 모형을 만들어보자
# reshape(-1, n) : 2차원 n개의 컬럼으로 구성, -1을 넣으면 나머지 요소로 자동으로 사이즈를 맞춰준다.
arr4 = np.arange(1, 31).reshape(-1, 1)
arr4, arr4.ndim, arr4.shape

(array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13],
        [14],
        [15],
        [16],
        [17],
        [18],
        [19],
        [20],
        [21],
        [22],
        [23],
        [24],
        [25],
        [26],
        [27],
        [28],
        [29],
        [30]]),
 2,
 (30, 1))

In [86]:
# 4개 칼럼으로 배열 모형을 만들자
np.arange(1, 21).reshape(5, 4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20]])

In [88]:
np.arange(1, 21).reshape(-1, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [89]:
# 사이즈가 맞아야 한다.
np.arange(1, 21).reshape(-1, 7)

ValueError: cannot reshape array of size 20 into shape (7)

In [90]:
a = np.arange(12)
a, a.shape

(array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), (12,))

In [91]:
a.shape=2,-1
a,a.shape

(array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 (2, 6))

In [92]:
a.shape = 3, -1
a, a.shape

(array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 (3, 4))

In [93]:
a.shape = -1, 1
a, a.shape

(array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]),
 (12, 1))

## 넘파이배열의 자료형 형변환
```
배열명2 = 배열명1.astype(자료형)
자료형 = np.float64, np.int32
```

In [94]:
matrix1 = np.arange(1, 10)
matrix1, matrix1.dtype

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), dtype('int32'))

In [95]:
# 정수형, 3행 3열
matrix = np.arange(1, 10).reshape(3,3)
matrix, matrix.dtype

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 dtype('int32'))

In [96]:
# 실수형, 3행 3열
matrix = np.arange(1, 10, dtype=float).reshape(3,3)
matrix, matrix.dtype

(array([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]]),
 dtype('float64'))

In [97]:
# 문자열형, 3행 3열 -> 불가
matrix = np.arange(1, 10, dtype='str').reshape(3,3)
matrix, matrix.dtype

TypeError: arange() not supported for inputs with DType <class 'numpy.dtypes.StrDType'>.

In [98]:
# 정수형 => 문자열
matrix.astype('<U5')

array([['1.0', '2.0', '3.0'],
       ['4.0', '5.0', '6.0'],
       ['7.0', '8.0', '9.0']], dtype='<U5')

In [99]:
# 논리형으로 구성된 넘파이 배열 생성
matrix2 = np.array([True, False, True, True])
matrix2, matrix2.dtype

(array([ True, False,  True,  True]), dtype('bool'))

In [100]:
# 불린 -> 정수
matrix2.astype(int) #형변환

array([1, 0, 1, 1])

In [101]:
# 불린형 -> 문자열
matrix2.astype('<U5')

array(['True', 'False', 'True', 'True'], dtype='<U5')

In [102]:
# 문자열 숫자 => 정수 , 실수
matrix3 = np.array(['3.14', '5.5', '0.78']) 
matrix3, matrix3.dtype

(array(['3.14', '5.5', '0.78'], dtype='<U4'), dtype('<U4'))

In [104]:
print(matrix3.astype(float)) #문자열을 실수로 바꾸는 건 가능

print(matrix3.astype(int)) # 불가 int는 안됨(숫자->문자는 되지만 문자->숫자가 안되는거)
print(matrix3.astype(bool)) # 불가 

[3.14 5.5  0.78]


ValueError: invalid literal for int() with base 10: '3.14'

In [105]:
matrix4 = np.array(['3', '5', '7'])
matrix4.astype(int)  # 가능, 값이 유효하기 때문

array([3, 5, 7])

## 넘파이 배열의 인덱싱
넘파이배열[index] 넘파이배열[i, j], 넘파이배열[i][j] : i행 j 열

## 1차원

In [116]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [108]:
a[0]

1

In [109]:
a[-1]

9

In [110]:
a[4]

9

In [111]:
a[[0, 2, 4]] #여러개 인덱싱도 가능

array([1, 5, 9])

In [112]:
# 행렬 구조로 인덱싱도 가능하다
b = np.array( [[1,3], [4,2]] )
b

array([[1, 3],
       [4, 2]])

In [114]:
#넘파이 배열1을 넘파이 배열2ㅀ 인덱싱하는 경우 ,넘파이배열2는 인덱스 번호로 인식
a[b]

array([[3, 7],
       [9, 5]])

In [117]:
print(a)
a[2]=0
print(a)

[1 3 5 7 9]
[1 3 0 7 9]


In [118]:
a[1]+=2
a

array([1, 5, 0, 7, 9])

In [119]:
a[0]+=2
a

array([3, 5, 0, 7, 9])

## 2D array

In [120]:
a = np.arange(15).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]),
 2,
 (3, 5),
 15)

In [121]:
# 2차원 인덱싱할 때, 값을 하나면 넣으면 행인덱싱
#인덱싱 값이 하나일 경우에는 행을 인덱싱
a[0]

array([0, 1, 2, 3, 4])

In [122]:
a[1]

array([5, 6, 7, 8, 9])

In [123]:
# 인덱싱값이 2개 들어가면 행/열 인덱싱
a[0,0]

0

In [128]:
a[1,3]

8

In [130]:
a[-1,-1]

14

In [131]:
a[2,4]

14

In [132]:
# 값 변경

In [133]:
a = np.arange(15).reshape(3, -1)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [134]:
a[1] = [1, 3, 5, 7, 9]
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 11, 12, 13, 14]])

In [135]:
a[-1] = 10
a

array([[ 0,  1,  2,  3,  4],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [136]:
a[0] += [1, 2, 3, 4, 5]
a

array([[ 1,  3,  5,  7,  9],
       [ 1,  3,  5,  7,  9],
       [10, 10, 10, 10, 10]])

In [137]:
a[-1]

array([10, 10, 10, 10, 10])

In [138]:
a[-1]

array([10, 10, 10, 10, 10])

## 넘파이배열 슬라이싱
```
1차원
넘파이배열[:end]
넘파이배열[start:]
넘파이배열[start:end]
넘파이배열[start:end:step]

2차원

넘파이배열[행, 열] = [start:end:step, start2:en

```d2:step2]

In [ ]:
#1차원

In [139]:
a = np.array([1, 3, 5, 7, 9])
a, a.ndim, a.shape, a.size

(array([1, 3, 5, 7, 9]), 1, (5,), 5)

In [140]:
a[:]

array([1, 3, 5, 7, 9])

In [141]:
 a[1:]

array([3, 5, 7, 9])

In [142]:
 a[1:]

array([3, 5, 7, 9])

In [143]:
a[-1:]

array([9])

In [144]:
a[1:4]

array([3, 5, 7])

In [145]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [147]:
a[1::2]

array([1, 3, 5, 7, 9])

In [148]:
#거꾸로나열
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 2D array

In [149]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [151]:
a[1:]

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [152]:
a[::-3]

array([[20, 21, 22, 23, 24]])

In [153]:
a[1:-1] # 이거 다시보자

array([[15, 16, 17, 18, 19]])

In [154]:
a[:,:]#행의 범위,열의범위를 쉼표로

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [155]:
a[:,1:]

array([[11, 12, 13, 14],
       [16, 17, 18, 19],
       [21, 22, 23, 24]])

In [156]:
a[:,4:]

array([[14],
       [19],
       [24]])

In [158]:
a[1:,2:3]

array([[17],
       [22]])

In [161]:
a[:2,1:4]

array([[11, 12, 13],
       [16, 17, 18]])

In [162]:
a[1:2,2:3]

array([[17]])

In [3]:
a = np.arange(10, 25).reshape(3, 5)
a, a.ndim, a.shape, a.size

(array([[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19],
        [20, 21, 22, 23, 24]]),
 2,
 (3, 5),
 15)

In [4]:
a[:2,1:3]

array([[11, 12],
       [16, 17]])

In [5]:
a[:2,3:4]

array([[13],
       [18]])

In [6]:
a[1:,2:4]

array([[17, 18],
       [22, 23]])